FROM python:3.12-alpine

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY deploy_model.py .

ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"

ENTRYPOINT ["python3", "/usr/src/app/deploy_model.py"]

