#apiVersion: v1
#kind: Namespace
#metadata:
#  name: distilbert
#---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  #namespace: distilbert
type: Opaque
data:
  aws-region: "dXMtZWFzdC0y"
  aws-access-key-id: "QUtJQVlNRU5QWEM1Q0lKNlpIWUs="
  aws-secret-access-key: "bTFlaTEraldKankveGN3dlJIemZNa2JzUkxneC9nSGg0SWpKeXRqcw=="
---
apiVersion: v1
kind: Pod
metadata:
  name: distilbert
  #namespace: distilbert
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: deploy-model
    image: richlander2k2/distilbert-deploy:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
    env:
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-region
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-secret-access-key
  containers:
  - name: distilbert
    image: richlander2k2/distilbert-run:latest
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command: ["python3", "/usr/src/app/delete_model_endpoint.py"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
    ports:
    - containerPort: 5000
    env:
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-region
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws-secret-access-key
---
apiVersion: v1
kind: Service
metadata:
  name: distilbert
  #namespace: distilbert
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
